from __future__ import annotations

import numpy as np
import pandas as pd


def score_u(p_df: pd.DataFrame, u_df: pd.DataFrame, seed: int = 42) -> np.ndarray:
    """
    目标：给 U 的每一行打一个“像正例 P”的分数（越大越像 P），用于从 U 中移除最不像 P 的一批。

    输入：
    - p_df：P.csv 读入的 DataFrame（正例，示例列：name, TM1, TM2, RMSD, iptm, DDG, FV_Charge, SAP_Score, seq）
    - u_df：U.csv 读入的 DataFrame（未标注，示例列：5design, iptm, pae_*, plddt_*, ptm, buns, ddg, fv_charge, sap_score, ...）
    - seed：随机种子（如算法含随机性，请使用它保证可复现）

    约束/注意：
    - 返回值必须是一维 np.ndarray，长度 == len(u_df)
    - 分数越大表示越像 P（越应该保留）；越小表示越不像 P（越应该被移除）
    - 需要对列名大小写/下划线差异更鲁棒（例如 DDG vs ddg，SAP_Score vs sap_score）
    - 需要处理 NaN/缺失值
    - P、U 列不一致时，只使用两者共同的“数值列”作为特征（避免 name/seq/5design 等 ID/序列列）
    """
    raise NotImplementedError("Implement score_u in this file (generated by NexAU).")
